TRUNCATE TABLE R_ORG_INVENTORY;
TRUNCATE TABLE R_ORG_BATCH_INVENTORY;
TRUNCATE TABLE R_INVENTORY_CHECK;
TRUNCATE TABLE R_INVENTORY_CHECK_DETAIL;
TRUNCATE TABLE R_ORG_AUDIT_RECORD;
TRUNCATE TABLE R_ORG_DRUG_APPLY;
TRUNCATE TABLE R_ORG_DRUG_APPLY_DETAIL;
TRUNCATE TABLE R_ORG_PREPAIR;
TRUNCATE TABLE R_ORG_PREPAIR_DETAIL;
TRUNCATE TABLE R_ORG_TRANS;
TRUNCATE TABLE R_ORG_TRANS_DETAIL;
TRUNCATE TABLE R_ORG_TRANS_HIS;
TRUNCATE TABLE R_ORG_TRANS_HIS_DETAIL;
TRUNCATE TABLE R_ORG_DELIVERY;
TRUNCATE TABLE R_ORG_DELIVERY_DETAIL;
TRUNCATE TABLE R_ORG_DELIVERY_APPLY;
TRUNCATE TABLE R_ORG_DELIVERY_TASK;
TRUNCATE TABLE R_ORG_DELIVERY_TASK_DETAIL;
TRUNCATE TABLE R_DRUG_ASSIGN;
TRUNCATE TABLE R_DRUG_ASSIGN_DETAIL;
TRUNCATE TABLE R_SERIAL_NUM;
TRUNCATE TABLE R_EM_CODE_RECORD;
TRUNCATE TABLE SYS_TRACKING;

UPDATE R_EM_CODE SET IS_LOCKED = 0, OWNER_ORG_ID = 'FF6A4197-F467658A-E04011AC-1D7F07AB', OWNER_ORG_NAME  = '九州医药', OWNER_DEPT_ID   = '476d4f7a-fe15-4956-af4f-b6a9e3a11746', OWNER_DEPT_NAME = '一号仓库';



